import Head from "next/head";
import { Fragment } from "react";
import PostForm from "../components/posts/postForm";

export default function Home() {
  return (
    <Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PostForm />
    </Fragment>
  );
}
