import Head from "next/head";
import { useContext } from "react";
import AuthContext from "../store/auth-context";

export default function Home() {
  const authCtx = useContext(AuthContext)

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>hello</h1>
      {authCtx.isLoggedIn && <p>Logged in</p>}
    </div>
  );
}

